// Code generated by girgen. DO NOT EDIT.

package gdk

// #cgo pkg-config: gobject-2.0
// #include <stdlib.h>
// #include <glib.h>
// #include <glib-object.h>
import "C"

const MAJOR_VERSION = 3
const MICRO_VERSION = 27
const MINOR_VERSION = 24
