// Code generated by girgen. DO NOT EDIT.

package gtk

import (
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gextras"
	"github.com/diamondburned/gotk4/pkg/core/girepository"
	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
)

// #cgo pkg-config: gobject-2.0
// #include <stdlib.h>
// #include <glib.h>
// #include <glib-object.h>
// extern void _gotk4_gtk3_CellRendererToggle_ConnectToggled(gpointer, gchar*, guintptr);
import "C"

// GType values.
var (
	GTypeCellRendererToggle = coreglib.Type(girepository.MustFind("Gtk", "CellRendererToggle").RegisteredGType())
)

func init() {
	coreglib.RegisterGValueMarshalers([]coreglib.TypeMarshaler{
		coreglib.TypeMarshaler{T: GTypeCellRendererToggle, F: marshalCellRendererToggle},
	})
}

// CellRendererToggleOverrides contains methods that are overridable.
type CellRendererToggleOverrides struct {
}

func defaultCellRendererToggleOverrides(v *CellRendererToggle) CellRendererToggleOverrides {
	return CellRendererToggleOverrides{}
}

// CellRendererToggle renders a toggle button in a cell. The button is drawn as
// a radio or a checkbutton, depending on the CellRendererToggle:radio property.
// When activated, it emits the CellRendererToggle::toggled signal.
type CellRendererToggle struct {
	_ [0]func() // equal guard
	CellRenderer
}

var (
	_ CellRendererer = (*CellRendererToggle)(nil)
)

func init() {
	coreglib.RegisterClassInfo[*CellRendererToggle, *CellRendererToggleClass, CellRendererToggleOverrides](
		GTypeCellRendererToggle,
		initCellRendererToggleClass,
		wrapCellRendererToggle,
		defaultCellRendererToggleOverrides,
	)
}

func initCellRendererToggleClass(gclass unsafe.Pointer, overrides CellRendererToggleOverrides, classInitFunc func(*CellRendererToggleClass)) {
	if classInitFunc != nil {
		class := (*CellRendererToggleClass)(gextras.NewStructNative(gclass))
		classInitFunc(class)
	}
}

func wrapCellRendererToggle(obj *coreglib.Object) *CellRendererToggle {
	return &CellRendererToggle{
		CellRenderer: CellRenderer{
			InitiallyUnowned: coreglib.InitiallyUnowned{
				Object: obj,
			},
		},
	}
}

func marshalCellRendererToggle(p uintptr) (interface{}, error) {
	return wrapCellRendererToggle(coreglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// ConnectToggled signal is emitted when the cell is toggled.
//
// It is the responsibility of the application to update the model with the
// correct value to store at path. Often this is simply the opposite of the
// value currently stored at path.
func (v *CellRendererToggle) ConnectToggled(f func(path string)) coreglib.SignalHandle {
	return coreglib.ConnectGeneratedClosure(v, "toggled", false, unsafe.Pointer(C._gotk4_gtk3_CellRendererToggle_ConnectToggled), f)
}

// CellRendererToggleClass: instance of this type is always passed by reference.
type CellRendererToggleClass struct {
	*cellRendererToggleClass
}

// cellRendererToggleClass is the struct that's finalized.
type cellRendererToggleClass struct {
	native unsafe.Pointer
}

var GIRInfoCellRendererToggleClass = girepository.MustFind("Gtk", "CellRendererToggleClass")
