// Code generated by girgen. DO NOT EDIT.

package gtk

// #cgo pkg-config: gobject-2.0
// #include <stdlib.h>
// #include <glib.h>
// #include <glib-object.h>
import "C"

// STOCK_DIALOG_AUTHENTICATION: “Authentication” item and icon.
//
// Deprecated: Use named icon &quot;dialog-password&quot;.
const STOCK_DIALOG_AUTHENTICATION = "gtk-dialog-authentication"

// STOCK_HARDDISK: “Harddisk” item and icon.
//
// Deprecated: Use named icon &quot;drive-harddisk&quot;.
const STOCK_HARDDISK = "gtk-harddisk"

// STOCK_INDENT: “Indent” item and icon. The icon has an RTL variant.
//
// Deprecated: Use named icon &quot;format-indent-more&quot;.
const STOCK_INDENT = "gtk-indent"

// STOCK_NETWORK: “Network” item and icon.
//
// Deprecated: Use named icon &quot;network-workgroup&quot;.
const STOCK_NETWORK = "gtk-network"

// STOCK_UNINDENT: “Unindent” item and icon. The icon has an RTL variant.
//
// Deprecated: Use named icon &quot;format-indent-less&quot;.
const STOCK_UNINDENT = "gtk-unindent"
