// Code generated by girgen. DO NOT EDIT.

package gtk

import (
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/atk"
	"github.com/diamondburned/gotk4/pkg/core/gextras"
	"github.com/diamondburned/gotk4/pkg/core/girepository"
	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
)

// #cgo pkg-config: gobject-2.0
// #include <stdlib.h>
// #include <glib.h>
// #include <glib-object.h>
import "C"

// GType values.
var (
	GTypeStackSwitcher = coreglib.Type(girepository.MustFind("Gtk", "StackSwitcher").RegisteredGType())
)

func init() {
	coreglib.RegisterGValueMarshalers([]coreglib.TypeMarshaler{
		coreglib.TypeMarshaler{T: GTypeStackSwitcher, F: marshalStackSwitcher},
	})
}

// StackSwitcherOverrides contains methods that are overridable.
type StackSwitcherOverrides struct {
}

func defaultStackSwitcherOverrides(v *StackSwitcher) StackSwitcherOverrides {
	return StackSwitcherOverrides{}
}

// StackSwitcher widget acts as a controller for a Stack; it shows a row of
// buttons to switch between the various pages of the associated stack widget.
//
// All the content for the buttons comes from the child properties of the Stack;
// the button visibility in a StackSwitcher widget is controlled by the
// visibility of the child in the Stack.
//
// It is possible to associate multiple StackSwitcher widgets with the same
// Stack widget.
//
// The GtkStackSwitcher widget was added in 3.10.
//
//
// CSS nodes
//
// GtkStackSwitcher has a single CSS node named stackswitcher and style class
// .stack-switcher.
//
// When circumstances require it, GtkStackSwitcher adds the .needs-attention
// style class to the widgets representing the stack pages.
type StackSwitcher struct {
	_ [0]func() // equal guard
	Box
}

var (
	_ Containerer       = (*StackSwitcher)(nil)
	_ coreglib.Objector = (*StackSwitcher)(nil)
)

func init() {
	coreglib.RegisterClassInfo[*StackSwitcher, *StackSwitcherClass, StackSwitcherOverrides](
		GTypeStackSwitcher,
		initStackSwitcherClass,
		wrapStackSwitcher,
		defaultStackSwitcherOverrides,
	)
}

func initStackSwitcherClass(gclass unsafe.Pointer, overrides StackSwitcherOverrides, classInitFunc func(*StackSwitcherClass)) {
	if classInitFunc != nil {
		class := (*StackSwitcherClass)(gextras.NewStructNative(gclass))
		classInitFunc(class)
	}
}

func wrapStackSwitcher(obj *coreglib.Object) *StackSwitcher {
	return &StackSwitcher{
		Box: Box{
			Container: Container{
				Widget: Widget{
					InitiallyUnowned: coreglib.InitiallyUnowned{
						Object: obj,
					},
					Object: obj,
					ImplementorIface: atk.ImplementorIface{
						Object: obj,
					},
					Buildable: Buildable{
						Object: obj,
					},
				},
			},
			Object: obj,
			Orientable: Orientable{
				Object: obj,
			},
		},
	}
}

func marshalStackSwitcher(p uintptr) (interface{}, error) {
	return wrapStackSwitcher(coreglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// StackSwitcherClass: instance of this type is always passed by reference.
type StackSwitcherClass struct {
	*stackSwitcherClass
}

// stackSwitcherClass is the struct that's finalized.
type stackSwitcherClass struct {
	native unsafe.Pointer
}

var GIRInfoStackSwitcherClass = girepository.MustFind("Gtk", "StackSwitcherClass")
