// Code generated by girgen. DO NOT EDIT.

package gtk

import (
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/atk"
	"github.com/diamondburned/gotk4/pkg/core/gextras"
	"github.com/diamondburned/gotk4/pkg/core/girepository"
	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
)

// #cgo pkg-config: gobject-2.0
// #include <stdlib.h>
// #include <glib.h>
// #include <glib-object.h>
import "C"

// GType values.
var (
	GTypeVScale = coreglib.Type(girepository.MustFind("Gtk", "VScale").RegisteredGType())
)

func init() {
	coreglib.RegisterGValueMarshalers([]coreglib.TypeMarshaler{
		coreglib.TypeMarshaler{T: GTypeVScale, F: marshalVScale},
	})
}

// VScaleOverrides contains methods that are overridable.
type VScaleOverrides struct {
}

func defaultVScaleOverrides(v *VScale) VScaleOverrides {
	return VScaleOverrides{}
}

// VScale widget is used to allow the user to select a value using a vertical
// slider. To create one, use gtk_hscale_new_with_range().
//
// The position to show the current value, and the number of decimal places
// shown can be set using the parent Scale class’s functions.
//
// GtkVScale has been deprecated, use Scale instead.
type VScale struct {
	_ [0]func() // equal guard
	Scale
}

var (
	_ Ranger = (*VScale)(nil)
)

func init() {
	coreglib.RegisterClassInfo[*VScale, *VScaleClass, VScaleOverrides](
		GTypeVScale,
		initVScaleClass,
		wrapVScale,
		defaultVScaleOverrides,
	)
}

func initVScaleClass(gclass unsafe.Pointer, overrides VScaleOverrides, classInitFunc func(*VScaleClass)) {
	if classInitFunc != nil {
		class := (*VScaleClass)(gextras.NewStructNative(gclass))
		classInitFunc(class)
	}
}

func wrapVScale(obj *coreglib.Object) *VScale {
	return &VScale{
		Scale: Scale{
			Range: Range{
				Widget: Widget{
					InitiallyUnowned: coreglib.InitiallyUnowned{
						Object: obj,
					},
					Object: obj,
					ImplementorIface: atk.ImplementorIface{
						Object: obj,
					},
					Buildable: Buildable{
						Object: obj,
					},
				},
				Object: obj,
				Orientable: Orientable{
					Object: obj,
				},
			},
		},
	}
}

func marshalVScale(p uintptr) (interface{}, error) {
	return wrapVScale(coreglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// VScaleClass: instance of this type is always passed by reference.
type VScaleClass struct {
	*vScaleClass
}

// vScaleClass is the struct that's finalized.
type vScaleClass struct {
	native unsafe.Pointer
}

var GIRInfoVScaleClass = girepository.MustFind("Gtk", "VScaleClass")
