// Code generated by girgen. DO NOT EDIT.

package pango

// #cgo pkg-config: gobject-2.0
// #include <stdlib.h>
// #include <glib.h>
// #include <glib-object.h>
import "C"

// ANALYSIS_FLAG_NEED_HYPHEN: whether to add a hyphen at the end of the run
// during shaping.
const ANALYSIS_FLAG_NEED_HYPHEN = 4
