// Code generated by girgen. DO NOT EDIT.

package gio

// #cgo pkg-config: gobject-2.0
// #include <stdlib.h>
// #include <glib.h>
// #include <glib-object.h>
import "C"

// FILE_ATTRIBUTE_TRASH_DELETION_DATE: key in the "trash" namespace. When
// requested against items in trash:///, will return the date and time when the
// file was trashed. The format of the returned string is YYYY-MM-DDThh:mm:ss.
// Corresponding AttributeType is G_FILE_ATTRIBUTE_TYPE_STRING.
const FILE_ATTRIBUTE_TRASH_DELETION_DATE = "trash::deletion-date"

// FILE_ATTRIBUTE_TRASH_ORIG_PATH: key in the "trash" namespace. When requested
// against items in trash:///, will return the original path to the file before
// it was trashed. Corresponding AttributeType is
// G_FILE_ATTRIBUTE_TYPE_BYTE_STRING.
const FILE_ATTRIBUTE_TRASH_ORIG_PATH = "trash::orig-path"
