// Code generated by girgen. DO NOT EDIT.

package gio

import (
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/girepository"
)

// #cgo pkg-config: gobject-2.0
// #include <stdlib.h>
// #include <glib.h>
// #include <glib-object.h>
import "C"

// OutputMessage: structure used for scatter/gather data output when sending
// multiple messages or packets in one go. You generally pass in an array of
// Vectors and the operation will use all the buffers as if they were one
// buffer.
//
// If address is NULL then the message is sent to the default receiver (as
// previously set by g_socket_connect()).
//
// An instance of this type is always passed by reference.
type OutputMessage struct {
	*outputMessage
}

// outputMessage is the struct that's finalized.
type outputMessage struct {
	native unsafe.Pointer
}

var GIRInfoOutputMessage = girepository.MustFind("Gio", "OutputMessage")
