// Code generated by girgen. DO NOT EDIT.

package atk

import (
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/girepository"
)

// #cgo pkg-config: gobject-2.0
// #include <stdlib.h>
// #include <glib.h>
// #include <glib-object.h>
import "C"

// TableCellIface: atkTableCell is an interface for cells inside an Table.
//
// An instance of this type is always passed by reference.
type TableCellIface struct {
	*tableCellIface
}

// tableCellIface is the struct that's finalized.
type tableCellIface struct {
	native unsafe.Pointer
}

var GIRInfoTableCellIface = girepository.MustFind("Atk", "TableCellIface")
